export const PATHS = {
    ADMIN: "/pages/admin",
    CONFIGS: "#",
    ERROR_401: "/pages/errors/401",
    ERROR_403: "/pages/errors/403",
    ERROR_404: "/pages/errors/404",
    ERROR_500: "/pages/errors/500",
    EVENTS: "/pages/admin/event",
    EVENT_ADD: "/pages/admin/event/add",
    EVENT_EDIT: "/pages/admin/event/edit",
    HOME: "/",
    LEADER: "/pages/leader",
    LEVELS: "/pages/admin/configs/levels",
    SECTORS: "/pages/admin/configs/sectors",
    USER: "/pages/user",
    USER_EDIT: "/pages/user/edit",
};
